# Enable pycodestyle (`E`) and Pyflakes (`F`) and flake8-type-checking (`TCH`) codes by default.
select = ["F", "E", "W", "I", "N", "D", "UP", "S", "C4", "DTZ", "EXE", "PT", "Q", "TCH", "PTH", "PD", "PGH", "TRY200", "TRY300", "NPY", "RUF"]
ignore = ["D401", "S101", "N806"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
# per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py310"
line-length = 119

[pydocstyle]
convention = "numpy"

# Ignore import violations in all `__init__.py` files.
[per-file-ignores]
"__init__.py" = ["D104", "E402", "F401", "F403", "F811"]